Resources:
  shortUrlsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: shortUrlsTable
      AttributeDefinitions:
        - AttributeName: urlId
          AttributeType: S
      KeySchema:
        - AttributeName: urlId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
